### ISSUE TITLE
Animation pauses while sending

### ISSUE THREAD

**Issue by fallerOfFalls** [appditto/natrium_wallet_flutter#31]
This is a minor, cosmetic bug. The little animation of blocks flowing away from the user that happens while sending, gets paused, and then resumes. Since the animation is meant to illustrate to the user that sending is happening, it's not really doing a good job. It worked fine in old Natrium. If it can't be fixed, could it simply be removed?

**Comment by bbedward** [comment]
What device and Natrium version? This was greatly improved in v2.0.3

**Comment by fallerOfFalls** [comment]
Device: Fairphone 2
Operating System: Lineage OS (android version 8.1.0)
Natrium version: 2.0.4

**Comment by bbedward** [comment]
Made significant strides to improve performance in 4bd465b8afe1cf3f171370834c5673663d1fc629

I can't exactly test the animation on my low-end phone because animations arent really working at all there (see: https://github.com/2d-inc/Flare-Flutter/issues/87)

Once v2.0.5 is released report back if you're still having issues.

**Comment by bbedward** [comment]
fixed by 48c0ea89c47de9f8603d4783f041f18f7b4da440
