### ISSUE TITLE
Unique addresses

### ISSUE THREAD

**Issue by Falsen** [appditto/natrium_wallet_flutter#42]
Since there is an security risk using only a single address for payments, it would be nice if you could generate new unique address for each payment. And then potentially have it automaticly manage the addresses behind the scenes.

This might be a bit too advanced, but I think it's crucial to have later on

**Comment by bbedward** [comment]
It's mainly for privacy, there's not any security risk re-using an address.

This works with BTC and others because addresses are generated from the same public key. You can re-use them, or you can not re-use them. Either way all of the funds end up in the same place.

With NANO that isn't the case. Generating new addresses means generating new accounts (a new private key and a new public key). If they re-use an old address then the app would need to generate a pow to receive it, generate a pow to send it, then send it to the new address.

It's just not really practical in NANO and doesn't make sense in the same way it does with like BTC.

There's other ideas being discussed for enhanced privacy such as "CAMO Banano" and mixers, some things like that we'd be up for integrating into the app
