### ISSUE TITLE
Gitlab Runner VM Advice

### ISSUE THREAD

**Issue by howardwkim** [appditto/natrium_wallet_flutter#56]
Hi Natrium, I was hoping to get your advice on setting up the build server for Gitlab.

We are using an in-house instance of Gitlab CE, and we are having difficulty configuring the build server for the Runner. 

Did you configure the build server from scratch? Or did you start with a preconfigured Docker container or image? Could you share any resources that helped you along this process?

Thank you.

**Comment by bbedward** [comment]
Hi Howard,

We configured the build server ourselves, it's a bare metal MacOS box. Docker doesn't work since we need to build and sign the iOS app (which can't be done in Linux, at least, can't be done in any supported way)

We wrote a whole guide about this that's pretty thorough, if you have any other questions I can help.

https://medium.com/@appditto/automate-your-flutter-workflow-using-gitlab-ci-cd-and-fastlane-5872e758165a

**Comment by howardwkim** [comment]
Thank you!
